# Generated by Django 3.0.8 on 2020-07-05 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='descrição')),
                ('tutor', models.CharField(max_length=30, verbose_name='tutor')),
                ('date', models.DateField(verbose_name='data')),
            ],
            options={
                'verbose_name': 'aula',
            },
        ),
    ]
